### ISSUE TITLE
Help with the setup:

### ISSUE THREAD

**Issue by felipebrunetti94** [scyv/scrum-poker#10]
Hi, could you help me with the setup and configs ?

**Comment by scyv** [comment]
Hi!

Yeah no problem. I will write an installation guide to help you (and others) there.

In the meantime you can use following steps:

* Install meteor: https://www.meteor.com/install
* Clone this repository
* Run on the command line: ``meteor npm install``
* Run on the command line: ``meteor``
* Go to http://localhost:3000

* There is no need for an account, just share the Link to a session.
* The username is stored in the local storage of the Browser

* Drawbacks:
  * All in German
  * Mobile usability is not good yet

* For Deployment, refer to https://guide.meteor.com/deployment.html
 
Hope this helps a little. Feel free to ask, if there are further questions... :-)

**Comment by felipebrunetti94** [comment]
@scyv thanks man, that is awesome... no problem with german when you have javascript kkk

**Comment by scyv** [comment]
I added some more information in the README file with commit d8098fff043e5a51fe7897ccf25d8ec17dee4b5c 
(I also updated to meteor 1.8.2)
