### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by j0h4nn3s** [scyv/scrum-poker#17]
I would like to introduce this tool at my company, but an English version is needed.

**Comment by scyv** [comment]
I will think about it, and maybe we get multilanguage in one of the next versions ;-)

**Comment by scyv** [comment]
The app now uses the default language of the browser (english and german are supported, english is fallback) => is that suitable, 
@j0h4nn3s ?  ;-)

**Comment by j0h4nn3s** [comment]
@scyv that sounds perfect, thanks for the quick implementation!
