### ISSUE TITLE
Tab-Preview in Safari shows revealed cards

### ISSUE THREAD

**Issue by drossel** [scyv/scrum-poker#23]
I am using Safari Version 15.3 (17612.4.9.1.8) on an MacBook Pro running macOS Monterey 12.2.1 with multiple tabs open. When I navigate to another tab (e.g. to check story details) and go back to the tab with poker.digital-scrum.de then the preview that I see while hovering over the tab shows the other participants estimates already revealed. After clicking the tab the cards are still hidden on the actual page.
![SafariPreview](https://user-images.githubusercontent.com/729583/155356427-de99056e-a4f6-4716-a9ee-04d273a97bf4.png)
![ActualPage](https://user-images.githubusercontent.com/729583/155356459-e24be9be-0501-4948-b039-8a59c6d84117.png)

**Comment by scyv** [comment]
@drossel Well.. very nice finding 😎 tab preview seems to have no support for css transformations 😬 i will fix that one…
